version: '3.1'
services:
  web:
    image: odoo:16.0
    # container_name: odoo-web-container
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons

  db:
    image: postgres:13
    # container_name: odoo-db-container
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo